CREATE DATABASE horse_race_simulator;
CREATE SEQUENCE race_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE horse_in_race_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE horse_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE race (id INT NOT NULL, active INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
        completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
        duration DOUBLE PRECISION DEFAULT NULL, max_distance DOUBLE PRECISION NOT NULL, PRIMARY KEY(id));
CREATE TABLE horse_in_race (id INT NOT NULL, horse_id INT NOT NULL, race_id INT NOT NULL, time_spent DOUBLE PRECISION NOT NULL, distance_covered DOUBLE PRECISION NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_4D38175576B275AD ON horse_in_race (horse_id);
CREATE INDEX IDX_4D3817556E59D40D ON horse_in_race (race_id);
CREATE TABLE horse (id INT NOT NULL, speed DOUBLE PRECISION NOT NULL, strength DOUBLE PRECISION NOT NULL, endurance DOUBLE PRECISION NOT NULL,
        best_speed DOUBLE PRECISION NOT NULL, autonomy DOUBLE PRECISION NOT NULL, slow_down DOUBLE PRECISION NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
ALTER TABLE horse_in_race ADD CONSTRAINT FK_4D38175576B275AD FOREIGN KEY (horse_id) REFERENCES horse (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE horse_in_race ADD CONSTRAINT FK_4D3817556E59D40D FOREIGN KEY (race_id) REFERENCES race (id) NOT DEFERRABLE INITIALLY IMMEDIATE;